### ISSUE TITLE
`RPA.Browser.Selenium` improvements

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#1081]
### 1 Sep 2023

- https://github.com/robocorp/rpaframework/issues/1080
- https://github.com/robocorp/rpaframework/issues/1078
- https://github.com/robocorp/documentation/issues/1022
- https://github.com/robocorp/rpaframework/issues/1079
- https://github.com/robocorp/rpaframework/issues/1075
- [x] Bump to latest **4.12** `selenium` and check behaviour.
- [x] Control `FORCE_32BIT` on IE webdriver downloading with an env var as well. (enabling 64bit)
- [x] Disable all SSL checks with `RC_DISABLE_SSL` (including webdriver-manager's)

**Comment by cmin764** [comment]
Released with **27.1.0**.
