### ISSUE TITLE
Automatic headless detection for RPA.Browser.Playwright

### ISSUE THREAD

**Issue by orlof** [robocorp/rpaframework#166]
I would like to be able to run the same code in my development environment (with browser window visible) and then transfer it to Robocorp Cloud for container headless runs - without modifying the headless=True argument.

**Comment by cmin764** [comment]
### ToDo
- [ ] Check current status
- [ ] Playwright: check if under cloud -> don't open a window (as it throws an error)
- [ ] Is it able to run with/out window using the same code? (automatic mode)

**Comment by tonnitommi** [comment]
@cmin764 close this if this is not very easy to implement
