### ISSUE TITLE
PDF library enhancements

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#243]
- [x] keyword `Get Text From PDF` with pages option is parsing whole file before getting text from specific page, for example PDF with 100 pages and you only want to get text from page 1
- [x] mute PDF dependency logging (especially visible when parsing bigger PDF files)
- [x] #287
- [ ] Documentation exhaustive examples for `Find Text` and `Get Text From PDF`, full "Open → Find → Set → Export" flow on the main page [doc](https://robocorp.com/docs/libraries/rpa-framework/rpa-pdf)

**Comment by cmin764** [comment]
Users are struggling with parsing some PDFs due to its complex format and not so obvious way to extract text under the hood. Sometimes is hard or impossible to extract texts from certain PDF inputs.

- Use **pdfminer** or some other tool in conjunction to what we have.
- Take into account too **OCRmyPDF** when dealing with images containing text in PDF docs. (usually happening with scanned docs)
- Improve docs with more examples.
- Gather a list of edge/business-case PDFs and automate robot testing over them so we make sure we support various inputs correctly.

Demo [script](https://gist.github.com/cmin764/7ddfada0d541ceaa91d724964403a0a3)

**Comment by orlof** [comment]
The problem with PDF lib parsing all pages before returning one page is that it takes so long with large PDF documents. If we can speed up the parsing, it doesn't really matter whether everything is parsed or not.

I think we are already using pdfminer as the pdf engine, but there are probably cases where it cannot parse pdfs. We should collect some test material to evaluate whether some other library would have better coverage.

If we integrate OCRmyPDF into RPAFW, should we spin PDF libraries into their own package (they are becoming quite large). Then there is also other PDF libraries that might be useful to integrate. E.g. Camelot provides special support for parsing tabular data from text based PDFs.
