### ISSUE TITLE
Documentation: Add information about "return" value to all keywords and overall library documentation update

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#318]
Closed due to the inactivity

**Comment by cmin764** [comment]
👌🏼 Totally agree + `-> <return_type>` from the function annotation/typing perspective to be exhaustive here.

And since we're at it and because it takes time to visit all these keywords, maybe it will make sense to also check the `robotframework` code examples in the docstrings for a standard on specifying (or not) the `*** Settings ***` and `*** Tasks ***` block headers since these are inconsistent now and producing or not code [highlight](https://rpaframework.org/libdoc/RPA_PDF.html#Find%20Text).

**Comment by cmin764** [comment]
Other potential subtasks (if not already covered these above):
- [ ] Make robocorp.com/docs pull, parse and display the `:returns:` value. (like on [`Find Text`](https://rpaframework.org/libdoc/RPA_PDF.html#Find%20Text) vs [`Find Text`](https://robocorp.com/docs/libraries/rpa-framework/rpa-pdf/keywords#find-text))
- [ ] Having a way of pulling `:raises:` as well from the docstring to display errors.
- [ ] Every keyword should have RF and Python examples. (RF uses `*** Settings ***` and `*** Tasks ***`, optionally `*** Keywords ***` headers as well and not having robocorp.com/docs adding them automatically as it breaks some edge cases -- linked [issue](https://github.com/robocorp/rpaframework/issues/280))
