### ISSUE TITLE
Work Items: Automatically parse and expose e-mail attachments

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#343]
When an e-mail triggers a Process in Control Room, we currently get the `rawEmail` and `parsedEmail` fields of the e-mail that triggered the process:
- `rawEmail`: raw string containing the entire e-mail as text (including multi-parts, text/html and attachments)
- `parsedEmail`: a dictionary containing all the items found and parsed from the e-mail above, including `Body` (post-parsed again if JSON/YAML format is detected)

Extra info to be added at runtime (but **not saved**) in the loaded input work item:
- `parsedEmail[Attachments]`: a list of strings containing the name of the files attached in the triggering e-mail
- Now `Get Work Item File(s)` will be able to retrieve these files (since they'll be [automatically](https://github.com/robocorp/rpaframework/blob/master/packages/main/src/RPA/Robocorp/WorkItems.py#L933) exposed in the input item)

### ToDo
- [ ] Ensure that sending an e-mail with attachments really triggers the process and if `rawEmail` contains the data of the attached files.
- [ ] Add a new entry into `parsedEmail` dictionary called `Attachments` which contains the names of the attached files found in the e-mail.
- [ ] Issuing `Get Work Item File    <name>` on each of those names will "download" and return the exposed attached file. (the obtained file path can be supplied to a new output work item or used just to read its content)
- [ ] Unit, robot tests, Control Room example
- [ ] Review, refactor/accept

### References
- [Pasi in community Slack](https://robocorp-developers.slack.com/archives/CVBU007LN/p1639053615130300)
- [Forum post](https://forum.robocorp.com/t/email-decoder-robot/1229)

**Comment by orlof** [comment]
This robot converts rawEmail to convenient work item for next step: https://github.com/robocorp/robot-email-decoder/blob/master/tasks.robot

Perhaps it's ok to have such robot as the first step in process, but I would still like to have library support for getting rid of those ugly `Evaluate` calls.

**Comment by cmin764** [comment]
> This robot converts rawEmail to convenient work item for next step: https://github.com/robocorp/robot-email-decoder/blob/master/tasks.robot
>
> Perhaps it's ok to have such robot as the first step in process, but I would still like to have library support for getting rid of those ugly Evaluate calls.

Looks good! From what I see, most of that robot final purpose is to iterate through attachments and put them into the next output work item. With the library improvement I'm proposing above, you should be able to call [`Get Work Item Files`](https://robocorp.com/docs/libraries/rpa-framework/rpa-robocorp-workitems/keywords#get-work-item-files) over the loaded initial input and get like that all the files of interest (like _*.xlsx_ ones) and then do stuff with them further.

A few notes on this:
- The files coming from the e-mail won't be saved in the input item, it will be felt like they're there, but won't appear in the Work Item data explorer in CR. (so if this item is passed to the next step ("Done item forwarding"), it won't interfere with the pipeline -- if and only if the user doesn't explicitly call "Save Work Item" on the input item in the robot code; if the user does call save, then I see it as a feature, what do you think @orlof / @mikahanninen ?)
- The files coming from the attachments won't interfere with the files normally attached in the Work Item since to my knowledge you can't trigger a Process by e-mail which will be started with an initial Work Item containing by default files. (the Cloud doesn't attach any, just "rawEmail" is in there)

If we don't want to pull files within the work item with `Get Work Item File(s)`, then we can put the files' content/paths in `parsedEmail["Attachments"] = [{"name": "my-file.xlsx", "path": "/path/to/file" | "content": b"file-bytes"}, ...]` if is more reasonable.

**Comment by cmin764** [comment]
Due to payload size limitation for sure this doesn't make sense anymore and the solution will come from the Control Room side as an Input Work Item containing in the payload the e-mail content (without attachments) and original attachments uploaded into S3 and retrievable as work item files.
