### ISSUE TITLE
Base `RPA.Windows` on core

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#404]
For convenience and better experience, we decided to include the new beta windows library into the main one as a referenced dependency.

### ToDo
- [x] 1. Sort out icons [PR](https://github.com/robocorp/rpaframework/pull/401) and up-to-date base from `RPA.Windows`. (and release latest _core_)
- [x] 2. Make `RPA.Windows` import common stuff from `RPA.core` while removing duplicate code.
- [ ] 3. Release latest _windows_ and link this dependency in _main_. (so _rpaframework_ brings latest _rpaframework-windows_ automatically -- fix docs meta-package deps)
- [x] 4. Add deprecation message in `RPA.Desktop.Windows` in favor of using `RPA.Windows` instead. (then release _main_)

**Comment by cmin764** [comment]
@mmokko / @mikahanninen Let me know if that's the right plan.
