### ISSUE TITLE
`RPA.Windows` 3.1.0 release

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#439]
Let's gather here what we want to get done for the next `rpaframework-windows` **3.1.0** release (mark what have been delivered with this release):
- [ ] Clicking with coordinates (we decided to not port this at this time -- and it's still available in the deprecated package anyways)
- [x] https://github.com/robocorp/rpaframework/issues/417
- [x] https://github.com/robocorp/rpaframework/issues/408
- [x] https://github.com/robocorp/rpaframework/issues/363
- [ ] https://github.com/robocorp/rpaframework/issues/446 (will be included in the next release)
