### ISSUE TITLE
Keep `RPA.Robocorp.WorkItems` compatible with "Parse email" Control Room option

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#485]
### Context
Currently the library automatically detects `rawEmail` in the payload and parses it into another configurable payload variable called: `parsedEmail`. This works fine with the old CR processes, but once we enable "Parse email" option, we'll have the parsed e-mail available into the `email` variable and the library will simply do nothing in the absence of the `rawEmail`. (so won't error, but **won't parse additionally either**, as we also detect JSON/YAML content and produce a dictionary out of it)

Legacy code for reference:
```robotframework
Get payload given e-mail process triggering
    ${mail} =    Get Work Item Variable    parsedEmail
    Log    ${mail}
    Set Work Item Variables    &{mail}[Body]
    Save Work Item
    ${message} =     Get Work Item Variable     message
    Should Be Equal     ${message}      from email
```
triggered with a JSON compatible text e-mail like:
```JSON
{
    "message": "from email"
}
```

### Blueprint
1. If `rawEmail` isn't found, look into `email.text` and if this is empty, then take the content of the Work Item file `__mail.html`.
2. At this stage we either have the e-mail parsed as dict from the library side (the legacy way with `rawEmail` -- option "Parse email" disabled) _OR_ we just place into the legacy `parsedEmail[Body]` payload variable the text/HTML content of the e-mail pulled from the new way at step **1.** (option "Parse email" enabled) + additional JSON/YAML detection & parsing. (which isn't handled on the Control Room side)
3. Put into `email.body` (if new parsed e-mail style is detected) a copy of the `parsedEmail[Body]` and recommend users to use `email.body` instead. (`parsedEmail` is always available for backwards compatibility no matter the CR state, but issuing a deprecation warning when used and the new e-mail parsing style is detected)

###### Objective
No matter if the parsing option is enabled or not in Control Room, users will always be able to retrieve with `Get Work Item Variable    parsedEmail` a dictionary containing in the `Body` key the value of the additionally parsed e-mail content. (destination payload variable name is configurable through `auto_parse_email` option during the importing of the `WorkItems` library; auto-parsing on the library side can be disabled entirely if set to `False`)

### ToDo
- [x] Code changes according to blueprint.
- [x] Update Work Items docs on the e-mail triggering side; show attachments retrieval examples as well.
- [x] Robot & unit tests.
- [x] Control Room tests with both the legacy behaviour and new parsed e-mail option activated.
- [ ] Enhance or create portal example show-casing this.
- [ ] Comment on [forum](https://forum.robocorp.com/t/email-decoder-robot/1229) with the new way.
- [ ] Answer on community Slacks having difficulties on getting the attachments. (since now is possible without additional library side parsing)

Related [issue](https://github.com/robocorp/rpaframework/issues/343)
