### ISSUE TITLE
Migrate from Selenium 3 to Selenium 4

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#494]
### Affected rpaframework "parts"

- `rpaframework-core` package ([webdriver-manager](https://pypi.org/project/webdriver-manager/) update)
- `rpaframework` package and especially `RPA.Browser.Selenium` library
- dependency `robotframework-seleniumlibrary` needs to be upgraded to minimum version of **6.0.0**
- dependency `robotframework-seleniumtestability` needs to be upgraded to minimum version of **2.0.0**
- example bots

### Other areas to be updated

- tests
- documentation

### Links

- [Article on the migration](https://www.browserstack.com/guide/upgrade-from-selenium-3-to-selenium-4)
- [List of Selenium API deprecations](https://www.selenium.dev/selenium/docs/api/java/deprecated-list.html)
- Battle testing [repo](https://github.com/mikahanninen/selenium4-battleground)

### TODO / problem areas

- [x] `core` package release with updated dependencies. (#607 )
- [x] Caching is tackled now by the `webdriver-manager`, so remove `webdriver.cache(browser)` usage from `Selenium`.
- [x] Custom `options` argument support in the OAB keyword. (#385 #258)
- [x] `DesiredCapabilities` got replaced by `Options`. (so our lib extensions should)
- [x] Go through all the [deprecated classes](https://www.selenium.dev/selenium/docs/api/java/deprecated-list.html) and cross-check with our internal usage. (library, examples, lib extensions)
- [x] Update release notes.
- [ ] `main` package release including updated `core` + changes to `RPA.Browser.Selenium`.
- [ ] The [Example Web Store Processor](https://github.com/robocorp/example-web-store-order-processor) (Portal) bot is using `find_element_by_class_name` on the returned `WebElement` object and that no longer exists. Need to be replaced with generic `find_element` and pass locator strategy as a first parameter.
- [x] Ask people for battle testing this before official release. (DevPI wheel and robot example)

###### Selenium 3
`${add_to_cart_button} =    Set Variable    ${product.find_element_by_class_name("btn_primary")}`

###### Selenium 4
`${add_to_cart_button} =    Set Variable    ${product.find_element("class name", "btn_primary")}`
