### ISSUE TITLE
`RPA.Browser.Selenium` doesn't detect conda-forge Firefox binary

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#516]
Using a robot keyword like `Selenium.Open Available Browser    https://www.google.com     browser_selection=firefox` won't work under a Firefox-ready _conda.yaml_ like:
```yaml
channels:
  # Define conda channels here.
  - conda-forge

dependencies:
  # Define conda packages here.
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search
  - python=3.7.5
  - firefox=100.0
  - geckodriver=0.30.0

  - pip=20.1
  - pip:
      # Define pip packages here.
      # https://pypi.org/
      - rpaframework==14.1.0 # https://rpaframework.org/releasenotes.html
```
since for some reason _firefox_ binary isn't found in `PATH` but _geckodriver_ works without setting it explicitly during the capabilities/options setting of the webdriver.

### Solution

Tested with this [robot](https://github.com/cmin764/robots/blob/main/browser-auto/tasks.robot#L70-L80):
```robotframework
Test Firefox
    # Using their keyword.
    Selenium.Open Firefox Site    https://www.google.com

    # Using our own RPA keyword.
    Selenium.Open Available Browser    https://www.google.com    headless=${HEADLESS}
    ...    browser_selection=firefox
```
and both of the calls work correctly now on a Mac. (problem doesn't replicate on Windows)

Therefore might be fixed with a patch like [this](https://github.com/cmin764/robots/blob/main/browser-auto/ExtendedSelenium.py#L42-L62):
```python
    @staticmethod
    def _set_firefox_binary(options):
        if "win32" in sys.platform:
            return
        
        # On *nix systems Firefox binary path still needs to be explicitly set.
        for path in os.getenv("PATH").strip().split(":"):
            if fnmatch.fnmatch(path, "*/holotree/*/bin"):
                # We just found the path containing firefox and geckodriver binaries.
                break
        else:
            raise Exception("Holotree path not found: please run with rcc/VSCode")
        
        options.binary_location = f"{path}/firefox"
    
    def _get_driver_args(self, browser, *args, **kwargs):
        # This is used with the `Open Available Browser` keyword.
        driver_args = super()._get_driver_args(browser, *args, **kwargs)
        if "firefox" in browser.lower():
            self._set_firefox_binary(driver_args[0]["options"])
        return driver_args
```
in our `RPA.Browser.Selenium` library. (tested and working on both Mac and Windows)

### ToDo:
- [ ] Investigate additionally this [problem](https://github.com/cmin764/robots/blob/main/browser-auto/ExtendedSelenium.py#L73-L75): `WebDriverException: Message: Can not connect to the Service /Users/cmin/.robocorp/holotree/b1f3c244e_9ba66f27/bin/firefox` (timebox it to half a day)
- [ ] PR with this or similar patch fixing the issue with running Firefox browser on Mac/Linux
- [ ] Additional tests in Control Room with: Linux container & custom env on a LightSail Windows 10 instance
- [ ] Optional unit & robot tests to test the patching triggering on `firefox` webdrivers

**Comment by bogdancondurache** [comment]
@cmin764 this seems to be an issue with Selenium: https://github.com/SeleniumHQ/selenium/issues/10686
Should we close this issue on our side and wait for it to get solved or just keep it in the backlog for tracking purposes?

**Comment by cmin764** [comment]
I'm closing it as not planned. (won't fix on our side, since should be on their's)

And for tracking purposes, we'll always have it on our "graveyard" and can be re-opened later on if it becomes something we need to fix on our side.
