### ISSUE TITLE
Align and reuse Invoke commands

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#564]
Currently [tasks_common.py](https://github.com/robocorp/rpaframework/blob/master/tasks_common.py) implements the _libspec_ related Invoke tasks and they are reused in all the other sub-packages tasks with this [idiom](https://github.com/robocorp/rpaframework/blob/master/packages/main/tasks.py#L14-L21):
```python
# Import rpaframework/tasks_common.py module from file location.
tasks_common_path = Path(__file__).parent.parent.parent / "tasks_common.py"
spec = importlib.util.spec_from_file_location("tasks_common", tasks_common_path)
tasks_common = importlib.util.module_from_spec(spec)
sys.modules["tasks_common"] = tasks_common
spec.loader.exec_module(tasks_common)

poetry = tasks_common.poetry
```
Therefore we can take advantage of this on including in _tasks_common.py_ any other function/constant we keep copy-pasting in each _tasks.py_ file. This DRY principle will add value when making a change (like fixing a bug) in one place instead of doing it everywhere and still missing some cases, thus improving development time, robustness and clarity. (proof [Issue](https://github.com/robocorp/rpaframework/issues/560))

### ToDo
- [x] Find identical patterns in every _tasks.py_ and move it to _tasks_common.py_ and reuse the function/constant from there.
- [x] See if there's a better alternative on importing the `tasks_common` module. (like playing with Python's PATH)
- [x] Be consistent on task names that are doing the very same thing among different packages. (e.g.: `testrobot` vs `test-robot`)

**Comment by cmin764** [comment]
@blakewaud fixed this with a common `invocations` module.
