### ISSUE TITLE
`RPA.Tables` Improvement TODOs

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#598]
Moved `TODO`s from _Tables.py_ module to this collating epic:
- [ ] Implement column slicing
- [ ] Index name conflict in exports/imports
- [ ] ~Return Robot Framework DotDict instead of dict?~

**Comment by mikahanninen** [comment]
on "Return Robot Framework DotDict instead of dict?"

**Comment by cmin764** [comment]
> on "Return Robot Framework DotDict instead of dict?"
> 
> why? what is the benefit ?

None I see, discarded.

- And I believe column slicing might be solved by [Pop Table Column](https://robocorp.com/docs/libraries/rpa-framework/rpa-tables/keywords#pop-table-column) over a `Copy Table`?
- What's with the "Index name conflict in exports/imports"? (@osrjv can shed some light here)

**Comment by osrjv** [comment]
If I remember correctly, you can dump tables into normal python objects in a way where the row index is one of the keys for the row. And I set a small reminder for myself that it will overwrite columns in the actual data called `index`. Not a very likely issue, but might happen.

DotDicts as output was a request from someone to support dot notation for accessing values for rows. It's a small improvement that might make sense, or maybe not. IIRC it's a subclass of dicts, so would not break the API, but you'd have to check that.

**Comment by tonnitommi** [comment]
Please re-open or create separate issues if there are need for RPA.Tables improvements
