### ISSUE TITLE
`RPA.Browser.*` library improvements (and Portal examples)

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#720]
## Frequent issues coming from the support side
- [ ] https://github.com/robocorp/rpaframework/issues/341 ([comment](https://github.com/robocorp/rpaframework/issues/341#issuecomment-1203815213))
- [ ] Portal example on selecting a certificate during the browser window prompt.
- [ ] Portal example with switching between windows & tabs. (@TejusVenkateshRobocorp )
- [ ] ~Add an example showcasing the `proxy` usage with the **OAB** keyword. (write a robot test for it as well to check behavior)~ (`proxy` is simply passed during library import)
- [x] Playwright external links: https://github.com/robocorp/rpaframework/issues/747
- [x] IE support: https://github.com/robocorp/rpaframework/issues/745
- [ ] Use Selenium's web-driver manager: https://github.com/robocorp/rpaframework/issues/777
- [x] #781
- [ ] Enable custom paths for the web-driver binary download location in _core_ (@mikahanninen )
- [x] Custom download: https://github.com/robocorp/rpaframework/issues/412

#### Selenium
- [x] https://github.com/robocorp/rpaframework/issues/883 🐛 
- [x] https://github.com/robocorp/rpaframework/issues/586 🐛 
- [x] #919
- [x] #920

#### Selenium
- [x] https://github.com/robocorp/rpaframework/issues/882
- [x] https://github.com/robocorp/rpaframework/issues/865
- [x] https://github.com/robocorp/rpaframework/issues/884
- [x] https://github.com/robocorp/rpaframework/issues/762
- [x] #940
- [x] #939
- [x] Fix `headless` unit-testing

#### Selenium
- [x] https://github.com/robocorp/rpaframework/issues/949 🐛 
- [x] #941

#### Playwright
- [x] #942
- [x] https://github.com/robocorp/rpaframework/issues/166
- [x] https://github.com/robocorp/rpaframework/issues/188

**Comment by TejusVenkateshRobocorp** [comment]
Can we look at the Open Available Browser to use alias parameter to help in the Switch Windows keyword? :)

**Comment by cmin764** [comment]
> Can we look at the Open Available Browser to use alias parameter to help in the Switch Windows keyword? :)

Definitely we can, the question is when. We can sync with Tommi on priorities

**Comment by cmin764** [comment]
I conclude this epic done now, will start another one with the rest of the unticked checkboxes when we'll consider those a priority again.
