### ISSUE TITLE
`RPA.Browser.Selenium` Investigate Internet Explorer support and add Portal example

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#745]
### ToDo
- [x] Apparently we can support IE with the following Selenium service: `selenium.webdriver.ie.webdriver.WebDriver`
  - And even the webdriver-manager we currently use supports managing it with: `webdriver_manager.microsoft.IEDriverManager`
  - ~So why not linking them both in order to support the old legacy IE as well. (required for some web apps working there only)~
  - Even if `ie` is used as browser, still just Edge will be launched in IE mode.
- [x] List all supported browsers right from the docs.
- [x] Portal example with the above.
  - As an alternative of using Edge in IE mode.
- [x] Link Portal example in the release notes and docs.

### Next
- Release **20.1.0**
- Check with our customer if this works as expected
