### ISSUE TITLE
Automatic template updates on new release

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#753]
PyPI publish trigger on CI for automatically updating the templates with the latest allowed major version of `rpaframework` in their _conda.yaml_s.

### ToDo
- [ ] PyPI hook that triggers when a release of `rpaframework` is successfully published.
- [ ] CI bot/flow which updates the templates with the latest allowed major version in PyPI.
- [ ] A way of specifying the latest allowed major version. (like a GH secret / env var as a rule -- something easy to change/increment)

**Comment by cmin764** [comment]
Placed this on the Roadmap again as we were discussing with @kariharju that we need a bot to update and keep templates in sync: to make the library upgrade PR, as it needs testing before having a green light on the merge and finally release it.
