### ISSUE TITLE
`RPA.Assistant` post-release improvements

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#775]
Gathering here a list of improvements that need to be brought after the first version of `RPA.Assistant` gets silently released.

Moved to https://github.com/robocorp/rpaframework/projects/5?add_cards_query=is:open
- [ ] ~Fix the `date_picker.DatePicker` widget so it renders years, months and days correctly.~
- [ ] ~Add a `debug` flag to the library itself, which could control if the log hiding `listener.register_protected_keywords(keywords)` is executed. Otherwise debugging when developing an Assistant with Robot Framework is pretty difficult~ 

As a continuation work of #682

**Comment by xylix** [comment]
* [ ] Implement support for other Location enums besides TopLeft and Center

(some sample code I wrote up during development)
```
    # TODO: implement (BottomLeft, BottomRight, TopRight)
    # elif location is Location.BottomRight:
    #     left_coordinate = screen_width
    #     top_coordinate = screen_height
    #     return (
    #         left_coordinate - window_width,
    #         top_coordinate - window_height,
    #     )
```

**Comment by xylix** [comment]
Possible idea: Add way for the UI to display errors (for example if a button fails to execute the callback code)

**Comment by xylix** [comment]
superceded by the project kanban https://github.com/robocorp/rpaframework/projects/5?add_cards_query=is:open
