### ISSUE TITLE
`RPA.PDF` improvements

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#785]
- [ ] https://github.com/robocorp/rpaframework/issues/784
- [ ] https://github.com/robocorp/rpaframework/issues/721
- [ ] https://github.com/robocorp/rpaframework/issues/551
- [ ] https://github.com/robocorp/rpaframework/issues/156
- [ ] https://github.com/robocorp/rpaframework/issues/103
