### ISSUE TITLE
`RPA.Windows` improvements

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#798]
- [x] https://github.com/robocorp/rpaframework/issues/797
- [x] https://github.com/robocorp/rpaframework/issues/796
- [x] https://github.com/robocorp/rpaframework/issues/791
- [x] https://github.com/robocorp/rpaframework/issues/704
- [ ] https://github.com/robocorp/rpaframework/issues/690
- [x] https://github.com/robocorp/rpaframework/issues/591
- [x] https://github.com/robocorp/rpaframework/issues/483
- [ ] https://github.com/robocorp/rpaframework/issues/800
- [x] https://github.com/robocorp/rpaframework/issues/820
- [x] Make `PrintTree` return as well: https://github.com/robocorp/rpaframework/issues/779
- [x] Check KeePass behaviour: https://github.com/robocorp/rpaframework/issues/806
- [x] @xylix Windows recording investigations: https://github.com/robocorp/rpaframework/pull/834
- [ ] https://github.com/robocorp/rpaframework/issues/802
- [x] https://github.com/robocorp/rpaframework/issues/871

**Comment by cmin764** [comment]
Extra closed issue (can be re-opened): https://github.com/robocorp/rpaframework/issues/779

Just in case this epic will provide a solution for it as well.

**Comment by xylix** [comment]
#834 added some error handling, but cases where user starts recording (`python -m RPA.Windows` or `windows-record`) if the first click is to desktop, there will be a weird error that makes the underlying library give out errors, and so for now the recording is aborted if this buggy behaviour happens.

But recording clicks on desktop works correctly if another application is clicked first. Unclear to me why initial clicks to desktop are so broken.
