### ISSUE TITLE
`rpaframework-windows` enable CI tests

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#802]
To strengthen and align the development of the Windows library with the rest, we need to enable CI automated tests on the following envs:
- Windows 10, 11
- Windows Server 2012 (and others frequently used by our customers)

During changes into the _windows_ package or _core_ that affects the _windows_ one, such tests should be triggered in order to ensure that the library still works and remains compatible with the upcoming merge.

### ToDo
- [ ] Provide and configure such dedicated envs. (at least Windows 10 for the start)
- [ ] Setup CI flow to trigger the tests under it.
- [ ] Enhance _core_ CI flow so it triggers such tests as well with the development _core_. (on _core_ changes) -- need some debate on this one @mikahanninen & @kariharju
