### ISSUE TITLE
Issues discovered during the Signature Matching Portal example

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#828]
Assistant version: **1.0.6**
Portal example robot used for testing: https://github.com/robocorp/example-signature-match-assistant

### Bugs

- [x] 2. `Add Text Input`: If you leave it untouched, you get nothing in the result dictionary, but if you type something inside and then you clear the whole content, then you get an empty string in the result dictionary. Is that intended? (and if "yes", then what's a valid use-case?) -- the example bot fails with `'' cannot be converted to a floating point number: ValueError: could not convert string to float: ''` when touching those text fields without letting a value inside at the end

### Not clear docs/behavior (confusing expectations)

- `Add Submit Buttons` states:
  > The dialog automatically creates a button for closing itself. If there are no input fields, the button will say "Close". If there are one or more input fields, the button will say "Submit".

  I saw no automatically generated buttons with the below example, did I miss something?
  ```robotframework
      Add Heading    Test
      Add text input    test
      Run dialog
  ```
  As only `Ask User` adds automatically "Submit"/"Close" buttons, no matter if we have input fields or not in the dialog.

  **Solution:** Either remove the misleading docs or implement the behavior.

- `Run Dialog` states:
  > None will let the operating system place the window.

  What does this mean? Is that belonging to the `location` param? And if yes, then by that "None" do we actually refer to `None`, meaning that the default behavior will let the OS decide where to place the dialog window?

  **Solution:** Reformat the docstring so the user understands to what param the `None` value addresses. (if is meant for "None" to refer to a value and not a pronoun in that decoupled sentence)

### Enhancements

- [x] `Add Text Input` (and others): Support for default values, as is tedious to check for every input if there is something passed and if there's nothing, then to assign a default. (will help with bug at **2.**)

### Nice to have

Fixes in https://github.com/robocorp/rpaframework/pull/829
- [x] added sliders
- [x] Keyword naming consistency, as there's some mixed case right now. (I'd vouch for `Camel Case Titles` kind of keyword names -- see Slack [thread](https://robocorptechnologies.slack.com/archives/CS71JM9T7/p1676038235347039?thread_ts=1676019215.970649&cid=CS71JM9T7))
- `Clear Dialog` states:
  > By default this is done automatically when a dialog is created.
  
  But I couldn't achieve the behavior without clearing the dialog explicitly by running the keyword [myself](https://github.com/robocorp/example-signature-match-assistant/blob/master/tasks.robot#L74) in the bot.

   - [x] **Solution:** `Run Dialog` to support a `clear=${True}` param which will clear after the result dictionary is obtained, so the next displayed dialog will start from a fresh state. (and `Ask User` will set `clear` to `True` by default)

**Comment by xylix** [comment]
Moved - [ ] `Add File Input` to provide feedback when a file is picked, so the user knows that he really picked something and what he picked. (displaying the file name in the button text or label or optionally add an additional entry which confirms the path to the file)
to backlog at https://github.com/robocorp/rpaframework/projects/5


The bug

 - [ ] 1. `Add File Input`: Relative paths don't work (nothing happens when you press the buttton).
   Expected: `Add File Input    source=devdata`; Workaround: `${source} =    Absolute Path    devdata` (and using the absolute path)

Is a won'tfix, with Flet supporting relative paths is just too much of a hassle.

**Comment by xylix** [comment]
Open parts were fixed by https://github.com/robocorp/rpaframework/pull/830
