### ISSUE TITLE
`RPA.Browser.Selenium`: Expand compatibility Chrome -> Chromium-based

### ISSUE THREAD

**Issue by ekipalen** [robocorp/rpaframework#865]
Add a possibility to open the Chromium-based Edge browser with the _use_profile_ argument.

At the same time, figure out which options are commonly supported by any Chromium-based browsers and enable those on these supported browsers. (as currently we set them for Chrome only, but they may work with others as well)

### ToDo
- [x] Add profile support for Chromium Edge
- [x] Understand which Chromium-based browsers we do support and what differences are between them.
- [x] Check if PDF page printing also works with other Chromium-based browsers. (and improve the error check limitation)
- [x] Check `proxy` support.
- [x] Setting of a download directory.
- [x] Check `Execute CDP` compatibility.

**Comment by cmin764** [comment]
Let's see if just applying the usual Chrome options to the other chromium based browsers as well (Edge, Brave etc.) will just work.
