### ISSUE TITLE
`RPA.Browser.Selenium`: Support custom download directory with Firefox as well

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#882]
According to this [thread](https://stackoverflow.com/a/69974916), one should be able to pass custom `options` to `Open Available Browser` or `Open Browser` keywords in such a way the **Firefox** browser will be able to download files inside the explicitly set directory.

⚠️ Currently, setting such a custom download directory is tested (and supported) mainly with **Chrome** only. (and Chromium-based browsers)

### ToDo
- [x] First of all, check if the behavior is supported at all through an `options` instance.
- [x] Then try extending the functionality with Firefox as well through the `Set Download Directory` keyword.
- [x] Test such custom download directory setting for the rest of the browsers.
- [x] Ensure the rendered `ROBOT` docstring is displayed correctly with this keyword. (relates to https://github.com/robocorp/rpaframework/issues/891)
- [x] See if there's a way to set a working download directory in _headless_ as well. (as only _headfull_ works for now)
- [x] Ensure best practices according to: https://github.com/robocorp/rpaframework/issues/741

Slack community [thread](https://robocorp-developers.slack.com/archives/C010E91EBA6/p1678700744736349)
Forum [post](https://forum.robocorp.com/t/set-default-download-directory-not-working/2461)

**Comment by cmin764** [comment]
### Chrome notes/fixes

> I have found a solution. The problem with downloads in old headless mode (“headless=old”) was caused by me deleting the "download.default_directory" value from "userProfilePreferences" object in driver options in config file.

[Stackoverflow](https://stackoverflow.com/questions/45631715/downloading-with-chrome-headless-and-selenium)
