### ISSUE TITLE
`RPA.Excel.*` improvements

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#921]
### `Files`
- [ ] https://github.com/robocorp/rpaframework/issues/122
- [ ] https://github.com/robocorp/rpaframework/issues/214
- [ ] https://github.com/robocorp/rpaframework/issues/262
- [ ] https://github.com/robocorp/rpaframework/issues/405
- [ ] https://github.com/robocorp/rpaframework/issues/406
- [ ] https://github.com/robocorp/rpaframework/issues/451
- [ ] https://github.com/robocorp/rpaframework/issues/651
- [ ] https://github.com/robocorp/rpaframework/issues/754
- [ ] https://github.com/robocorp/rpaframework/issues/761
- [ ] https://github.com/robocorp/rpaframework/issues/858

### `Application`
- [ ] https://github.com/robocorp/rpaframework/issues/218
- [ ] https://github.com/robocorp/rpaframework/issues/462
- [ ] https://github.com/robocorp/rpaframework/issues/630
