### ISSUE TITLE
`RPA.Robocorp.*` improvements

### ISSUE THREAD

**Issue by cmin764** [robocorp/rpaframework#929]
- [ ] https://github.com/robocorp/rpaframework/issues/845
- [ ] https://github.com/robocorp/rpaframework/issues/746
- [ ] https://github.com/robocorp/rpaframework/issues/744
- [ ] https://github.com/robocorp/rpaframework/issues/707
- [ ] https://github.com/robocorp/rpaframework/issues/458
- [ ] https://github.com/robocorp/rpaframework/issues/257
- [ ] https://github.com/robocorp/rpaframework/issues/668
- [ ] https://github.com/robocorp/rpaframework/issues/845
- [ ] https://github.com/robocorp/rpaframework/issues/596
